### ISSUE TITLE
The Extension shows no bookmarks

### ISSUE THREAD

**Issue by CodingFan72** [jackiotyu/vscode-browser-bookmark#1]
Hi,

I have installed the extension but when I open the sidebar I can't find any bookmark.

I get the message: "Es ist kein Datenanbieter registriert, der Sichtdaten bereitstellen kann."
Translation: There is no data provider registered that can provide visibility data.

What do I need to do to access bookmarks?

**Comment by jackiotyu** [comment]
Have you install chrome in your computer? Please give more information about the error, such as screenshots.

**Comment by CodingFan72** [comment]
Hello,
Thank you for your quick response.
Chrome is installed on my computer and set as the default browser:
Version 118.0.5993.118 (Official Build) (64-bit)

I also believe that the extension doesn't "connect" to Chrome.

When I open the sidebar this is all I see:

[cid:005cf2ed-d4ee-4ee4-b822-df1e340d1ec8]

What want you to see also?


________________________________
Von: Huang Bingfeng ***@***.***>
Gesendet: Montag, 30. Oktober 2023 12:44
An: jackiotyu/vscode-browser-bookmark ***@***.***>
Cc: CodingFan72 ***@***.***>; Author ***@***.***>
Betreff: Re: [jackiotyu/vscode-browser-bookmark] The Extension shows no bookmarks (Issue #1)


Have you install chrome in your computer? Please give more information about the error, such as screenshots.

**Comment by jackiotyu** [comment]
Please let me know what platform you are using now.

**Comment by CodingFan72** [comment]
I use Windows 10
Version 22H2 (Build 19045.3570)

**Comment by CodingFan72** [comment]
Hi,
Thanks to the ability to set the path manually, I can now access my bookmarks. 👍

**Comment by CodingFan72** [comment]
This solves my problem.
