### ISSUE TITLE
Command 'XXX' not found

### ISSUE THREAD

**Issue by CodingFan72** [jackiotyu/vscode-browser-bookmark#2]
Hi

when I use the sidebar and click one of the buttons I get the following message(s):

`command 'browser-bookmark.refresh' not found`
`command 'browser-bookmark.search' not found`
`command 'browser-bookmark.openSetting' not found`

What do I have to do in order to use the buttons?

**Comment by jackiotyu** [comment]
Looks like you got a initialization error, do you install chrome? This extension needs chrome installed for collecting bookmarks.

**Comment by CodingFan72** [comment]
Hello,
Thank you for your quick response.
Chrome is installed on my computer and set as the default browser:
Version 118.0.5993.118 (Official Build) (64-bit)

Which info do you need also?
________________________________
Von: Huang Bingfeng ***@***.***>
Gesendet: Montag, 30. Oktober 2023 12:54
An: jackiotyu/vscode-browser-bookmark ***@***.***>
Cc: CodingFan72 ***@***.***>; Author ***@***.***>
Betreff: Re: [jackiotyu/vscode-browser-bookmark] Command 'XXX' not found (Issue #2)


Looks like you got a initialization error, do you install chrome? This extension needs chrome installed for collecting bookmarks.

**Comment by jackiotyu** [comment]
Please check the config path, you can find it by open new tab with "chrome://version/" through chrome.

![preview](https://github-production-user-asset-6210df.s3.amazonaws.com/31788042/279085203-ffde4601-506a-4a36-9c04-ef29160ad3ec.png)
<img width="920" alt="image" src="https://github.com/jackiotyu/vscode-browser-bookmark/assets/31788042/59bab053-4928-465f-84a6-e51b8cf94ce2">

I will update the extension to fix the initialization error  soon.😃

**Comment by jackiotyu** [comment]
Please try the latest version, hope it can be fixed.

**Comment by CodingFan72** [comment]
Thank you for releasing the update quickly.
Unfortunately nothing has changed.

Here my chrome config path

[cid:95678e04-7b5c-4a78-b733-7044112ba8a8]

[cid:8b03942c-cd29-4159-acc9-43b305d3a5fa]

________________________________
Von: Huang Bingfeng ***@***.***>
Gesendet: Montag, 30. Oktober 2023 15:36
An: jackiotyu/vscode-browser-bookmark ***@***.***>
Cc: CodingFan72 ***@***.***>; Author ***@***.***>
Betreff: Re: [jackiotyu/vscode-browser-bookmark] Command 'XXX' not found (Issue #2)


Please try the latest version, hope it can be fixed.

**Comment by jackiotyu** [comment]
Oh, I can't get the image from your answer.😥
Please send it through github? Is the path end with "Chrome/Default" ?

**Comment by CodingFan72** [comment]
![image](https://github.com/jackiotyu/vscode-browser-bookmark/assets/76176989/88e5c2f7-b72b-4236-b84c-2699067debd5)
![image](https://github.com/jackiotyu/vscode-browser-bookmark/assets/76176989/2b2977b3-eba9-4a6c-9f85-abb68fc59544)

**Comment by jackiotyu** [comment]
Okay, your profile path is special, let me provide a config for the bookmark file path. Please wait a moment.

**Comment by jackiotyu** [comment]
<img width="1380" alt="image" src="https://github.com/jackiotyu/vscode-browser-bookmark/assets/31788042/46b83baf-5c20-4351-8ea1-4ed55a3fecd2">

I have update the extension, and please configure the bookmark file path follow this steps.
Make sure fill the whole path, includes "Bookmarks",  such as "a/b/Bookmarks".
It will work after you save, click "refresh" to verify it.
Thank for install this extension. 😀

**Comment by CodingFan72** [comment]
Great, thank you very much for the opportunity to set up the path.

I have no idea why my path is abnormal.
But abnormal suits me 😉.

The ability to set the path manually means I now have access to my bookmarks. 👍

**Comment by CodingFan72** [comment]
This solves my problem.

**Comment by jackiotyu** [comment]
Maybe more convenience by such setting😀, I will add it later

![image](https://github.com/jackiotyu/vscode-browser-bookmark/assets/31788042/31cd9008-3528-4d30-aa44-0f294aeb4645)
![image](https://github.com/jackiotyu/vscode-browser-bookmark/assets/31788042/832595a5-af17-4944-abc6-a9dd3cb8bdc7)
